spring.application.name=quizgenerator
spring.ai.google.genai.api-key=my-api-key
spring.mongodb.uri=my-mongodb-database
logging.level.org.springframework.security=DEBUG
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=my-email-address
spring.mail.password=my-email-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true